### ISSUE TITLE
item stats are located in LIST_JEMITEM.STB ?

### ISSUE THREAD

**Issue by laurenzzo** [eRose-DatabaseCleaning/STB#1]
test by changing a value is needed

**Comment by hdelanno** [comment]
Yes, they are.
An item, as it is by default, can have one "stat". Either the gem stat or the "normal blue stats". Those stats are listed in this STB file. With the first 100 (?) lines for normal apparaisal stats, the next 40 (?) for quest/donate item stats and then stats from gems.
You can find this in Calculation.cpp [1] in the sources. It is the variable GEM_OP.

[1] https://github.com/PurpleYouko/Wibble_Wibble/blob/master/Rose_Engine/Client/Common/Calculation.cpp#L218-L275 (for evo but still gives the idea)
