### ISSUE TITLE
difference between LIST_ZONEZ.STB and LIST_ZONE.STB ?

### ISSUE THREAD

**Issue by laurenzzo** [eRose-DatabaseCleaning/STB#6]

**Comment by hdelanno** [comment]
For this kind of question, one has to look into the source code and to make a search in it. To improve results, also search for "3DData".

A lot of STB files are loaded here: https://github.com/PurpleYouko/Wibble_Wibble/blob/4b31d6735e1d25d159e422eb2210c7e9f6e519f9/Rose_Engine/Client/System/CGame.cpp#L607 

Just note... it is evo! So the STB are different than the ones used for Arcturus. But it can give you an idea ;) (For example Arcturus doesn't have LIST_BREAK.STB or don't use the (new) list for items (<-to be checked? But was already checked I think)

**Comment by laurenzzo** [comment]
no result with LIST_ZONEZ.STB
I believe we can remove it from the client and server files

**Comment by laurenzzo** [comment]
note : File is already missing :+1:
